version: '3.1'

services:
  backend:
    build: ./cactsu-server
    ports:
      - "3000:3000"
    depends_on:
      - frontend
    restart: on-failure
    environment:
      - MODE_RUN=docker-compose
  frontend:
    build: ./cactsu-client
    ports:
      - "5173:5173"
  db:
    image: "postgres:16.2"
    ports:
      - "5433:5432"
    environment:
      # - POSTGRES_PASSWORD=DBPassword
      # - POSTGRES_USER=UserName
      # - POSTGRES_DB=DBName